### ISSUE TITLE
getting `Error: Property name "constructor" is not allowed in "model" data` when trying to create a new model

### ISSUE THREAD

**Issue by thaerlabs** [Tallyb/loopback-graphql#44]
First of all, thanks for creating this package, I'll be more than happy to help contribute, but I'm trying to get it running and I'm stuck on creating models, login and queries are fine. But not create mutations.

`loopback --> 3.0.0`
`loopback-graphql --> 0.10.0`

I have a `company` Model with only a `name` attribute.

the query I'm trying to run:

```
mutation {
  createcompany(data: {name: "super company"}) {
    name
  }
}
```

```
Error: Property name "constructor" is not allowed in "model" data
    at ModelConstructor.ModelBaseClass._initProperties (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/model.js:77:11)
    at ModelConstructor.ModelBaseClass (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/model.js:58:8)
    at ModelConstructor (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/model-builder.js:185:22)
    at ModelConstructor (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/model-builder.js:185:22)
    at new ModelConstructor (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/model-builder.js:185:22)
    at Function.DataAccessObject.create (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/loopback-datasource-juggler/lib/dao.js:287:11)
    at Promise.denodeify (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/nodegit-promise/lib/node-extensions.js:24:20)
    at tryCallTwo (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/nodegit-promise/lib/core.js:45:5)
    at doResolve (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/nodegit-promise/lib/core.js:173:13)
    at new Promise (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/nodegit-promise/lib/core.js:65:3)
    at Function.Promise.denodeify (/Users/thabbas/Projects/code/loopback/loopback-demo/node_modules/nodegit-promise/lib/node-extensions.js:19:12)
```

The contents of `model.js` in loopback `loopback-datasource-juggler` at that exception:

```
ModelBaseClass.prototype._initProperties = function(data, options) {
  var self = this;
  var ctor = this.constructor;

  if (typeof data !== 'undefined' &&
      typeof (data.constructor) !== 'function') { // ERRORS HERE
    throw new Error(g.f('Property name "{{constructor}}" is not allowed in %s data', ctor.modelName));
  }
```

Which is weird, as the error states *'Property name "{{constructor}}" is not allowed in <model> data'*, but in the code, it's throwing the error if the passed data doesn't have a `constructor`. 😅 

I'm not sure if it's an issue with `loobpack-graphql` or `loopback-datasource-juggler`. 

Please let me know if more explanation or help is needed

**Comment by thaerlabs** [comment]
Apparently it's already reported over there https://github.com/strongloop/loopback-datasource-juggler/issues/1261

**Comment by Tallyb** [comment]
Yes, I should publish a new version, as I have already created a work
around for it.

**Comment by thaerlabs** [comment]
@Tallyb I also opened a PR on loopback side, https://github.com/strongloop/loopback-datasource-juggler/pull/1284

**Comment by Tallyb** [comment]
@thaerlabs please check if 0.12.0 provides a fix. If not - please re-open

**Comment by thaerlabs** [comment]
@Tallyb PR merged from loopback's side 🎉 , hopefully it'll be in the next release of https://github.com/strongloop/loopback-datasource-juggler.

I think you can remove the workaround implemented.

https://github.com/strongloop/loopback-datasource-juggler
